server:
  port: 3000
  env: development
  read_timeout: 10s
  write_timeout: 10s
  shutdown_timeout: 5s

database:
  host: localhost
  port: 5432
  name: timebride
  user: postgres
  password: secret
  max_open_conns: 25
  max_idle_conns: 25
  conn_max_lifetime: 5m

redis:
  host: localhost
  port: 6379
  db: 0
  pool_size: 10

jwt:
  secret: your-secret-key
  expires_in: 24h
  refresh_expires_in: 720h

cors:
  allowed_origins:
    - http://localhost:3000
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed_headers:
    - Origin
    - Content-Type
    - Accept
    - Authorization
