services:
  db:
    image: postgres:15
    container_name: timebride-db  # Фіксоване ім'я контейнера
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: timebride-redis  # Фіксоване ім'я контейнера
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: timebride-app
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=timebride
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVER_PORT=3000
      - SERVER_HOST=0.0.0.0
      - JWT_SECRET=myTimeBrideSecretForJwtTokens123456
      - TEMPLATE_DIR=./web/templates
      - STATIC_DIR=./web/static
      - PUBLIC_DIR=./web/public
      - CONTROLLERS_DIR=./web/controllers
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app/web:delegated
      - ./config:/app/config:delegated
      - ./migrations:/app/migrations:delegated
      - ./internal:/app/internal:delegated
      - ./.env:/app/.env:delegated
      - /app/node_modules
    restart: unless-stopped

volumes:
  pgdata:
  redis_data:

networks:
  default:
    name: timebride-network