# Scaling Configuration

# Cache settings
cache:
  enabled: true
  type: "redis"  # Options: redis, memcached, in-memory
  redis:
    host: "localhost"
    port: 6379
    password: ""
    db: 0
    pool_size: 10
    idle_timeout: 300  # seconds
  memcached:
    servers: ["localhost:11211"]
  in_memory:
    max_size: 1000  # Maximum number of items
    ttl: 3600  # Time to live in seconds

# Load balancing settings
load_balancer:
  enabled: true
  type: "round_robin"  # Options: round_robin, least_connections, ip_hash
  health_check:
    interval: 30  # seconds
    timeout: 5    # seconds
    unhealthy_threshold: 3
    healthy_threshold: 2
    path: "/health"

# Horizontal scaling settings
horizontal_scaling:
  enabled: true
  auto_scaling:
    enabled: true
    min_instances: 2
    max_instances: 10
    scale_up_threshold: 80  # CPU usage percentage
    scale_down_threshold: 20  # CPU usage percentage
    cooldown_period: 300  # seconds
  session_storage:
    type: "redis"  # Options: redis, database
    redis:
      host: "localhost"
      port: 6379
      password: ""
      db: 1
    database:
      table: "sessions"
      cleanup_interval: 3600  # seconds

# Database scaling
database:
  read_replicas:
    enabled: true
    count: 2
    load_balancing: "round_robin"
  connection_pool:
    max_open_connections: 25
    max_idle_connections: 10
    connection_lifetime: 3600  # seconds
    idle_timeout: 300  # seconds

# File storage scaling
file_storage:
  type: "s3"  # Options: s3, local, distributed
  s3:
    region: "us-east-1"
    bucket: "timebride-files"
    endpoint: ""  # For custom S3-compatible storage
    access_key: ""
    secret_key: ""
  distributed:
    nodes: ["node1", "node2", "node3"]
    replication_factor: 2

# API rate limiting
rate_limiting:
  enabled: true
  type: "redis"  # Options: redis, in-memory
  redis:
    host: "localhost"
    port: 6379
    password: ""
    db: 2
  limits:
    default: 100  # requests per minute
    authenticated: 300  # requests per minute
    premium: 1000  # requests per minute

# Monitoring and metrics
monitoring:
  enabled: true
  prometheus:
    enabled: true
    port: 9090
  grafana:
    enabled: true
    port: 3000
  alerting:
    enabled: true
    channels:
      - type: "email"
        recipients: ["admin@timebride.com"]
      - type: "slack"
        webhook: "https://hooks.slack.com/services/xxx/yyy/zzz" 